name: "PR Checks"
on: [pull_request, push]

permissions: {}

jobs:
  check_pr:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: "npm ci"
      run: npm ci

    - name: "npm run build"
      run: npm run build

    - name: "npm run test"
      run: npm run test

    - name: "check for uncommitted changes"
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
                 "and check in all changes" \
            && exit 1)
